//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.25 at 05:10:19 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/PMOTask", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.services.projects.model;
